name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-deploy:
    name: Setup & Deploy to Cloud Storage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      - name: yarn install & build
        run: |
          yarn -v
          yarn install
          yarn run build

      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Upload to Cloud Storage
        run: |-
          gsutil -h "Cache-Control:public, max-age=30" -m cp -r build/* gs://buzzle-live
